### PR TITLE
EHC-148: Navbar is shown in save to pdf functionality

### PR DESCRIPTION
**Pull request by NamkhangNLe**
Add "noPrint" class to sidebar component in sidebar.js and update styles.css to hide the sidebar when printing

### CODE REVIEW

**Review by dsoman24 — CHANGES_REQUESTED** [review]
Looks good, but we should not merge before we fix the issue with not all pages showing.

**Comment by NamkhangNLe** [comment]
> Looks good, but we should not merge before we fix the issue with not all pages showing. 

Yup! Working on that now just wanted to make incremental changes

**Comment by NamkhangNLe** [comment]
@edong36 @thespych  Having a bit of difficulty connecting the checkboxes to print each trend accordingly. 

1. Tried to use jspdf and shove all the trends inside to no avail
2. HTML2Canvas doesn't work because we're calling MongoDB and the trends are not available in the DOM 
3. Am looking into somehow printing each trend separately with a new page but as it stands the fact that it isn't in the DOM natively and we instead using command+p makes it quite difficult

**Review by morganbroome — APPROVED** [review]
Looks good

**Review by dsoman24 — APPROVED** [review]
Looks good. Just make sure to carefully resolve merge conflicts

**Pull request merged**
