### PR TITLE
UI Changes & Improvements

### PR DESCRIPTION
**Pull request by NamkhangNLe**
Changed button colors for links on home page.

### CODE REVIEW

**Comment by dsoman24** [comment]
Some thoughts:
- In the patient list, instead of text buttons for view, edit, delete, we should have intuitive icons e.g. eye for view, pencil for edit, trashcan for delete. No text on these buttons would make the UI cleaner, especially when the data table gets filled with entries.
- For the create patient, could we add a plus icon as well as the text?
- Buttons should all be consistent. Delete button and create patient should also have rounded corners

We can leave retexturing the other buttons on other pages for another PR or maybe sprint 5.

**Comment by NamkhangNLe** [comment]
> Some thoughts:
> 
> - In the patient list, instead of text buttons for view, edit, delete, we should have intuitive icons e.g. eye for view, pencil for edit, trashcan for delete. No text on these buttons would make the UI cleaner, especially when the data table gets filled with entries.
> 
> - For the create patient, could we add a plus icon as well as the text?
> 
> - Buttons should all be consistent. Delete button and create patient should also have rounded corners
> 
> 
> 
> We can leave retexturing the other buttons on other pages for another PR or maybe sprint 5. 

I like the idea of icons for the button. The reason I had different for delete was to make it not be clicked accidentally.

**Comment by dsoman24** [comment]
> > Some thoughts:
> > 
> > * In the patient list, instead of text buttons for view, edit, delete, we should have intuitive icons e.g. eye for view, pencil for edit, trashcan for delete. No text on these buttons would make the UI cleaner, especially when the data table gets filled with entries.
> > * For the create patient, could we add a plus icon as well as the text?
> > * Buttons should all be consistent. Delete button and create patient should also have rounded corners
> > 
> > We can leave retexturing the other buttons on other pages for another PR or maybe sprint 5.
> 
> I like the idea of icons for the button. The reason I had different for delete was to make it not be clicked accidentally.

What we could add is a deletion confirmation popup to avoid that

**Review by morganbroome — COMMENTED** [review]
I like Daniel's idea

**Pull request closed without merging**
