### PR TITLE
Added ability to select multiple meds.

### PR DESCRIPTION
**Pull request by thespych**
Users can now select multiple medications from the checkbox. Medications are stored as an array in the database under the "medications" field. 

Edited the patient list to have the number of meds show up, rather than all the meds. This can be changed in future if Rebecca has abbreviations for them.

### CODE REVIEW

**Review by dsoman24 — COMMENTED** [review]
Adding comment so this counts as a review, my other comment wasnt.

**Review by edong36 — CHANGES_REQUESTED** [review]
It seems that only one medication can be checked on the patient form. It may have to do with the updateForm logic.

**Review by MichaelEHammond — CHANGES_REQUESTED** [review]
Eric is right, only one medication can be selected. The idea is that we can select multiple and then have them saved with the calculation. That way, they know what medications the patient is on with each calculation.

**Comment by thespych** [comment]
Wait, are you guys referring to the calculation page? or the update patient page? If so I am able to select and deselect multiple meds simulatenously on the update patient page and have them properly save to the database.

**Comment by thespych** [comment]
OHH okay wait i see what yall are talking about. I changed updateForm for when editing patients but not for when creating patients (thought they used the same logic). Should be fixed now, as well as updated the category header to "Number of Medications" as per daniel's request.

**Review by edong36 — APPROVED** [review]

**Review by MichaelEHammond — APPROVED** [review]
This should fix it! Great work.

**Pull request merged**
