### PR TITLE
Added CSV Download

### PR DESCRIPTION
**Pull request by thespych**
Added ability to download data for a specific calculation as a CSV.

Created the new file "Table.js" in order to do so, since I needed a specific component for the table in order to implement this feature in (believe me, I tried to not do it this way. it's just easier this way lol). 

When a user clicks the button "Download to CSV", it should download the data in tabular format to a CSV file to the user's computer.

csv
download

### CODE REVIEW

**Comment by dsoman24** [comment]
Overall looks good. I like that you moved the code away to another component! A bit cleaner/more modular. 

Could the csv file be named according to the patient initials and formula type like "ss_addition_{download date}.csv" or something like that? Could be easier for users instead of ending up with a bunch of data.csv, data (1).csv, etc. 

Not sure if we talked about this but should we add feature to download all data at once into one big CSV?

**Comment by thespych** [comment]
Downloading all data is a bit harder as we'd need to refactor. Gonna merge this in now and change the name of the file in next update

**Comment by thespych** [comment]
CSV filename now matches calculation

**Review by MichaelEHammond — APPROVED** [review]
Moving this to its own component will be beneficial in the long run. CSV name now fits calculation, so approved! In the future we should look at how to get all data in one CSV.

**Pull request merged**
